apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml

patches:
  - path: deployment-update.yaml
    target:
      kind: Deployment
      name: socket-manager
  - path: ingress.yaml
    target:
      kind: Ingress
      name: socket-manager

configMapGenerator:
  - name: socket-manager-env-config
    envs:
      - config.env
    options:
      disableNameSuffixHash: true
