apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - ../base
  - ingress.yaml
patches:
  - path: deployment-update.yaml
    target:
      kind: Deployment
      name: socket-manager

configMapGenerator:
  - name: socket-manager-env-config
    envs:
      - config.env
    options:
      disableNameSuffixHash: true
