apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: data
          emptyDir: { }
      containers:
        - name: redis
          image: redis:7.2.0
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /var/lib/redis/data
              subPath: redis
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
