spring:
  application:
    name: socket-manager
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password:
logging:
  level:
    root: INFO

